# Usar uma imagem base do Node.js 
# Definir diretorio
FROM node:22-alpine
WORKDIR /app
# Copiar e instalar arquivos do npm e dependências
COPY package*.json ./
RUN npm install
# Copiar todos os arquivos do projeto
COPY . .
# Run the tests in the container
# Expor a porta usada pelo servidor de desenvolvimento
EXPOSE 3000
# Iniciar o servidor de desenvolvimento
CMD ["npm", "start"]
