# Usar uma imagem base do Go para desenvolvimento
FROM golang:1.22-alpine
WORKDIR /internship-project
# Copiar os arquivos de configuração do Go e baixar as dependências
COPY go.mod go.sum ./
RUN go mod download
# Copiar todos os arquivos do projeto
COPY . .
# Run the tests in the container

EXPOSE 8080
# Iniciar o servidor de desenvolvimento
CMD ["go", "run", "./cmd"]
