services:
  db:
    image: mysql:8.0
    healthcheck:
      test: "exit 0"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: internship_project

  backend:
    build:
      context: ./taskstodo
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - ./taskstodo/db:/taskstodo/db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: mypassword
      DB_NAME: internship_project

  frontend:
    build:
      context: ./front-taskstodo
      dockerfile: Dockerfile
    ports:
      - "80:80"

volumes:
  db_data:
