# Start the development server
## Use a Node.js base image
FROM node:22-alpine
WORKDIR /app
## Copy and install npm files and dependencies
COPY package*.json ./
RUN npm install
# Copy files and expose
COPY . .
EXPOSE 3000
CMD ["npm", "start"]
