# Start the production server
## Use a Go base image
FROM docker-hub.artifactory.globoi.com/golang:1.22-alpine
WORKDIR /taskstodo 
## Copy and install npm files and dependencies
COPY go.mod go.sum ./
RUN go mod download
# Copy files , enable cgo and expose
COPY . .
EXPOSE 8080
CMD ["go", "run", "./cmd"]