# Use a Go base image
FROM golang:1.22-alpine
WORKDIR /taskstodo 

# Copy Go modules files and download dependencies
COPY go.mod go.sum ./
RUN go mod download
# Add necessary build tools
RUN apk add --no-cache gcc musl-dev
# Copy all files
COPY . .
ENV CGO_ENABLED=1
EXPOSE 8080
CMD ["go", "run", "./cmd"]